# Generated by Django 2.1.1 on 2018-10-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_uuid_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=4)),
                ('release', models.DateField()),
            ],
        ),
    ]
