# Generated by Django 2.1.1 on 2018-10-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_author_category_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
