# MODEL
# id = models.UUIDField(default=uuid.uuid4,  unique=True, primary_key=True)
# uuid=models.UUIDField(default=uuid.uuid4, blank=True)

# Generated by Django 2.1.1 on 2018-10-12 03:49

from django.db import migrations, models
import uuid

MYAPP = 'webapp'
PMODEL = 'Author'
FMODEL = 'Post'
FKTO = 'webapp.Author'
FFIELD = 'author'
PREMIGRATION = '0013_remove_author_uuid'

# Update Relation in Line 30
# RELATION = 'id=fmod.author'


def create_uuid(apps, schema_editor):
    Pmods = apps.get_model(MYAPP, PMODEL)
    for pmod in Pmods.objects.all():
        pmod.uuid = uuid.uuid4()
        pmod.save()

def match(apps, schema_editor):
    Fmods = apps.get_model(MYAPP, FMODEL)
    Pmods = apps.get_model(MYAPP, PMODEL)
    for fmod in Fmods.objects.all():
        pmod = Pmods.objects.get(id=fmod.author)
        fmod.temp_field = pmod.uuid
        fmod.save()


class Migration(migrations.Migration):

    dependencies = [
        (MYAPP, PREMIGRATION),
    ]

    operations = [

        migrations.AddField(
            model_name=PMODEL,
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),

        migrations.RunPython(create_uuid),

        migrations.AlterField(
            model_name=FMODEL,
            name=FFIELD,
            field=models.CharField(max_length=100,null=True)
        ),

        migrations.AlterField(
            model_name=PMODEL,
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True)
        ),

        migrations.AddField(
            model_name=FMODEL,
            name='temp_field',
            field=models.UUIDField(blank=True, null=True)
        ),

        migrations.RunPython(match),

        migrations.RemoveField(
            model_name=PMODEL,
            name='id',
        ),

        migrations.AlterField(
            model_name=PMODEL,
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),

        migrations.RenameField(
            model_name=PMODEL,
            old_name='uuid',
            new_name='id',
        ),

        migrations.RemoveField(
            model_name=FMODEL,
            name=FFIELD,
        ),
        
        migrations.RenameField(
            model_name=FMODEL,
            old_name='temp_field',
            new_name=FFIELD,
        ),

        migrations.AlterField(
            model_name=FMODEL,
            name=FFIELD,
            field=models.ForeignKey(blank=True, to=FKTO, on_delete=models.CASCADE, null=True),
        ),
    ]
